import { StyleSheet } from "react-native";

import { COLORS, FONT, SIZES } from "../../../constants";

const styles = StyleSheet.create({
  container: {
    width: "100%",
  },
  userName: {
    fontFamily: FONT.regular,
    fontSize: SIZES.large,
    color: COLORS.secondary,
  },
  welcomeMessage: {
    fontFamily: FONT.bold,
    fontSize: SIZES.xLarge,
    color: COLORS.primary,
    marginTop: 2,
  },
  searchContainer: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: SIZES.large,
    height: 50,
  },
  searchWrapper: {
    flex: 1,
    backgroundColor: COLORS.white,
    marginRight: SIZES.small,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: SIZES.medium,
    height: "100%",
  },
  searchInput: {
    fontFamily: FONT.regular,
    width: "100%",
    height: "100%",
    paddingHorizontal: SIZES.medium,
  },
  searchBtn: {
    width: 50,
    height: "100%",
    backgroundColor: COLORS.tertiary,
    borderRadius: SIZES.medium,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBtnImage: {
    width: "50%",
    height: "50%",
    tintColor: COLORS.white,
  },
  tabsContainer: {
    width: "100%",
    marginTop: SIZES.medium,
  },
  tab: (activeJobType, item) => ({
    paddingVertical: SIZES.small / 2,
    paddingHorizontal: SIZES.small,
    borderRadius: SIZES.medium,
    borderWidth: 1,
    borderColor: activeJobType === item ? COLORS.secondary : COLORS.gray2,
  }),
  tabText: (activeJobType, item) => ({
    fontFamily: FONT.medium,
    color: activeJobType === item ? COLORS.secondary : COLORS.gray2,
  }),

  resumeUploadContainer: {
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: 10,
    borderWidth: 2,
    borderColor: "#ccc",
    borderStyle: "dashed",
    paddingBottom: 10,
  },
  msgText: {
    width: "100%",
    textAlign: "center",
    flexWrap: "wrap",
    alignSelf: "center",
    marginTop: 20,
    fontFamily: FONT.regular,
    width: "100%",
    height: "100%",
    paddingHorizontal: SIZES.medium,
  },
  plusIcon: {
    marginBottom: 20,
    padding: 20,
    width: 60,
    height: 60,
  },
  resumeUploadButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  resumeUploadbtn: {
    alignSelf: "center",
    backgroundColor: "#856BE3",
    borderRadius: 10,
    width: "55%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: 10,
    marginRight:10,
    borderColor: "#ccc",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
    paddingRight: 5,
  },
  uploadBtnText: {
    alignSelf: "center",
    fontFamily: FONT.regular,
    width: "100%",
    height: "100%",
    paddingHorizontal: SIZES.medium,
    color: "#fff",
  },
  cancelBtn: {
    alignSelf: "center",
    backgroundColor: "#f72556",
    borderRadius: 10,
    width: "35%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: 10,
    borderColor: "#ccc",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
    paddingRight: 5,
  },
});

export default styles;
